### ISSUE TITLE
Example showing SQL/NoSQL database interactions

### ISSUE THREAD

**Issue by Nexuist** [faastjs/examples#7]
Hello,

I'm not at all familiar with this framework but it looks extremely interesting so I was going through some examples. It would be extremely beneficial, for a lot of people I think, if you had an example showing a simple CRUD app that interacted with DynamoDB etc. since quite a lot of serverless functions have a database component. I'm especially interested in how I can set up IAM roles for the functions I have defined in code.

**Comment by acchou** [comment]
Thanks for the suggestion!

By default, faast.js will create an IAM role for your lambda function that has administrator privileges, so you should be able to do anything with it. If you prefer to use a different role, you can use the [RoleName option](https://faastjs.org/docs/api/faastjs.awsoptions.rolename#awsoptionsrolename-property).

While it's entirely possible to use faast.js to interact with a database, putting it into a CRUD app is not exactly in the sweet spot unless the app needs to spawn lots of small tasks that can be run in parallel. If you have some use case in mind I can try to come up with an example.
